imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi:             ~
    #translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form:
        resources:    ['bootstrap_3_layout.html.twig']

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }



# Parsing
app:
    debug:     false
    sites:
        -
            name:               "heinigerag"
            logo:               "heinigerag.png"
            language:           ["de"]
            EAN:                false
            searchType:         "urlQuery"
            parseUrl:           "http://www.shop.heinigerag.ch/de/search?q="

            baseUrl:            "http://shop.heinigerag.ch"
            formID:             "#quicksearch"
            inputKey:           "q"
            formInputs:
                    sort:           "relevance|desc"
            mainNode:           "div.item.media"
            titleNode:
                    value:          "h4.media-heading > a"
                    type:           "innerHTML"
            priceNode:
                    value:          "span.price"
                    type:           "innerHTML"
            urlNode:
                    value:          "h4.media-heading > a"
                    type:           "relative"
            imageNode:
                    value:          "div.media-left > a > img"
                    type:           "relative"



        -
            name:               "melectronics"
            logo:               "melectronics.png"
            language:           ["fr", "de", "it"]
            EAN:                true
            searchType:         "urlQuery"
            parseUrl:           "http://www.melectronics.ch/c/fr/?q="

            baseUrl:            "http://www.melectronics.ch"
            formID:             null
            inputKey:           null
            formInputs:         null
            #formID:             "#searchbox"
            #inputKey:           "q"
            #formInputs:         null
            mainNode:           "div.listing > ul > li"
            titleNode:
                    value:          "h3.productname"
                    type:           "innerHTML"
            priceNode:
                    value:          "span.price > span.current"
                    type:           "innerHTML"
            urlNode:
                    value:          "div.productcell > div.content > a"
                    type:           "relative"
            imageNode:
                    value:          "span.product > img"
                    type:           "absolute"



        -
            name:               "hawk"
            logo:               "hawk.png"
            language:           ["de"]
            EAN:                true
            searchType:         "urlQuery"
            parseUrl:           "http://www.hawk.ch/catalogsearch/result/?q="

            baseUrl:            "http://www.hawk.ch"
            formID:             null
            inputKey:           null
            formInputs:         null
            #formID:             "#search_mini_form"
            #inputKey:           "q"
            #formInputs:         null
            mainNode:           "ul.products-grid > li.item"
            titleNode:
                    value:          "h2.product-name a"
                    type:           "title"
            priceNode:
                    value:          "span.price"
                    type:           "innerHTML"
            urlNode:
                    value:          "h2.product-name > a"
                    type:           "absolute"
            imageNode:
                    value:          "a.product-image > img"
                    type:           "absolute"



        -
            name:               "STEG"
            logo:               "steg.png"
            language:           ["fr", "de", "it"]
            EAN:                false
            searchType:         "urlQuery"
            parseUrl:           "http://www.steg-electronics.ch/fr/article/articleSearch.aspx?TXTSEARCH="

            baseUrl:            "http://www.steg-electronics.ch"
            formID:             null
            inputKey:           null
            formInputs:         null
            #formID:             "#searchForm"
            #inputKey:           "query"
            #formInputs:         null
            mainNode:           "article.articleItem"
            titleNode:
                    value:          "div.articleData > div.nameAndDescription > h3 > a"
                    type:           "innerHTML"
            priceNode:
                    value:          "div.priceAndAddToCart > div.priceWrapper > div > div.actualPrice"
                    type:           "innerHTML"
            urlNode:
                    value:          "div.articleData > div.nameAndDescription > h3 > a"
                    type:           "relative"
            imageNode:
                    value:          "div.leftPanel > a > img"
                    type:           "relative"



        -
            name:               "Mediamarkt"
            logo:               "mediamarkt.png"
            language:           ["fr", "de", "it"]
            EAN:                true
            searchType:         "urlQuery"
            parseUrl:           "https://shop.mediamarkt.ch/fr/search/?s="

            baseUrl:            "https://shop.mediamarkt.ch"
            formID:             null
            inputKey:           null
            formInputs:         null
            mainNode:           "div#div_searchResults > div.prod-4"
            titleNode:
                    value:          "div > div > div.prod-4-4 > div.div-40 > a > h2"
                    type:           "innerHTML"
            priceNode:
                    value:          "div > div > div.prod-4-3 > div.price-4 > span"
                    type:           "innerHTML"
            urlNode:
                    value:          "div > div > div.prod-4-4 > div.div-40 > a"
                    type:           "relative"
            imageNode:
                    value:          "div > div > div.prod-4-1 > a > span > img"
                    type:           "absolute"



        -
            name:               "Microspot"
            logo:               "microspot.png"
            language:           ["fr", "de"]
            EAN:                false
            searchType:         "urlQuery"
            parseUrl:           "http://www.microspot.ch/msp/pages/searchResult.jsf?searchTerm="

            baseUrl:            "http://www.microspot.ch"
            formID:             null
            inputKey:           null
            formInputs:         null
            mainNode:           "table.biglist > tbody > tr"
            titleNode:
                    value:          "td.productList_specColumn > div.specColumn_content > h3 > a > span"
                    type:           "innerHTML"
            priceNode:
                    value:          "td.productList_priceInfoColumn > div.priceContent > span.productList_price"
                    type:           "innerHTML"
            urlNode:
                    value:          "td.productList_specColumn > div.specColumn_content > h3 > a"
                    type:           "relative"
            imageNode:
                    value:          "td.productList_pictureColumn > a > img"
                    type:           "relative"



#        -
#            name:               "Galaxus"
#            logo:               "galaxus.svg"
#            language:           ["fr", "de", "it"]
#            EAN:                false
#            searchType:         "urlQuery"
#            parseUrl:           "https://www.galaxus.ch/fr/Search?searchSectors=0&q="
#
#            baseUrl:            "https://www.galaxus.ch"
#            formID:             null
#            inputKey:           null
#            formInputs:         null
#            mainNode:           "article.product"
#            titleNode:
#                    value:          "div.product-name"
#                    type:           "innerHTML"
#            priceNode:
#                    value:          "div.product-price"
#                    type:           "innerHTML"
#            urlNode:
#                    value:          "div.product-buttons > a.product-overlay"
#                    type:           "relative"
#            imageNode:
#                    value:          "div.product-image > div > img"
#                    type:           "absolute"



#        -
#            name:               "Fust"
#            logo:               "fust.png"
#            language:           ["fr", "de", "it"]
#            EAN:                true
#            searchType:         "urlQuery"
#            parseUrl:           "https://www.fust.ch/fr/home.html?searchtext="
#
#            baseUrl:            "https://www.fust.ch"
#            formID:             null
#            inputKey:           null
#            formInputs:         null
#            mainNode:           "ul.results > li"
#            titleNode:
#                    value:          "section.product > div.content-wrapper > div.title-wrapper > h3 > a"
#                    type:           "innerHTML"
#            priceNode:
#                    value:          "section.product > div.order-wrapper > div.endprice"
#                    type:           "innerHTML"
#            urlNode:
#                    value:          "section.product > div.content-wrapper > div.title-wrapper > h3 > a"
#                    type:           "relative"
#            imageNode:
#                    value:          "section.product > figure > a > img.lazy"
#                    type:           "relative"